### ISSUE TITLE
Market depth and Mode

### ISSUE THREAD

**Issue by Obsessive** [zerodhatech/pykiteconnect#30]
No matter what the mode is set to (in my case I have tried ws.MODE_FULL), the incoming data says
```
'depth': {}, 
mode': 'quote', 
...
```

Why are the market depth and mode behaving like this? is this known?

please help,
Thanks :)

**Comment by vividvilla** [comment]
For what instrument token you have tried subscribing?

**Comment by Obsessive** [comment]
subscribed to over 30 instruments.. 

response is something like this 
```{'tradeable': True, 'mode': 'quote', 'instrument_token': 387841, 'last_price': 135.75, 'last_quantity': 4, 'average_price': 136.34, 'volume': 311384, 'buy_quantity': 421903, 'sell_quantity': 671826, 'ohlc': {'open': 137.25, 'high': 137.9, 'low': 135.2, 'close': 137.25}, 'change': -1.092896174863388, 'depth': {}}
```
 
mode set is full.

**Comment by vividvilla** [comment]
You can see in the response is mode is set to `quote`. Possible that you are not setting mode correctly . Can you post your code how you set mode?
