### ISSUE TITLE
Using access_token in the url returns 400 bad request.

### ISSUE THREAD

**Issue by kkaushy** [zerodhatech/pykiteconnect#32]
https://github.com/zerodhatech/pykiteconnect/blob/06e352f873f049bed3c3e6051f32ecc725e990c4/kiteconnect/ticker.py#L442

When trying to run the example code from the repository, I am getting bad request when websocket is trying to connect.
After changing the access_token key to public_token, request are getting successfull.

**Comment by vividvilla** [comment]
You were connecting to current version of Kite ticker url. In recent commit we have updated the default url to new server url. Please update and check.
