### ISSUE TITLE
Need procedure for installing kiteconnect on pycharm 2018.3.5

### ISSUE THREAD

**Issue by sagaranilganu** [zerodhatech/pykiteconnect#57]
Am in desperate need of a proper procedure for installing kiteconnect on pycharm 2018.3.5

Current configuration with me is ::
1) pycharm 2018.3.5
2) pip 10.0.1
3) Build Tools for Visual Studio 2017
4) Windows 8.1 OS - 64 bit

Tried n number of ways to install MSVC 14.0 and upgrading pip to newer version 19.0.3 but fails every time.

Whoever using the workable method please share!!!

**Comment by vividvilla** [comment]
Can you please share the stack trace you get on failed installation?

**Comment by sagaranilganu** [comment]
Thanks, but got it installed by "downgrading" the python interpreter from 3.7 to 3.6!!! 
But to its dismay it's now demanding "api_key & access_token". 
I first need to "build n back test my strategies" and then buy the subscription (sandbox is not available).
Pls share any other way to get "Intraday Nifty FnO data on 1 min basis" (NSEpy provides daily not intraday)
