### ISSUE TITLE
kite.positions() do not return the latest data.

### ISSUE THREAD

**Issue by surru** [zerodhatech/pykiteconnect#62]
Whenever I do kite.positiions(), I never recieve the latest data. I request you to fix this on priority.

**Comment by surru** [comment]
Any update on this ?

**Comment by vividvilla** [comment]
This seems like an API issue, can you please post it on Kite trade forum here - https://kite.trade/forum/discussions

**Comment by surru** [comment]
Posted on forum : https://kite.trade/forum/discussion/6511/
