### ISSUE TITLE
TypeError: place_order() missing 1 required positional argument: 'variety'

### ISSUE THREAD

**Issue by kinhalkarrushikesh123** [zerodhatech/pykiteconnect#66]
here you need and extra argument and have to specify variety

**Comment by grsb007** [comment]
Is there any solution for this?

**Comment by vividvilla** [comment]
As per documentation `variety` is a mandatory field - https://kite.trade/docs/pykiteconnect/v3/#kiteconnect.KiteConnect.place_order

**Comment by c3phalik** [comment]
It's pretty straightforward. Check the code below
`order_id = kite.place_order(tradingsymbol='ITC',
                                        exchange=kite.EXCHANGE_NSE,
                                        transaction_type=kite.TRANSACTION_TYPE_BUY,
                                        quantity=1,
                                        order_type=kite.ORDER_TYPE_MARKET,
                                        product=kite.PRODUCT_CNC,
                                        variety=kite.VARIETY_AMO)`

Variety can have the following values:

- kite.VARIETY_AMO

- kite.VARIETY_BO

- kite.VARIETY_CO

- kite.VARIETY_REGULAR

**Comment by vividvilla** [comment]
Closing the issue since author didn't get back.
