### ISSUE TITLE
Multiple Instruments not receiving ticks

### ISSUE THREAD

**Issue by karthickbala123** [zerodhatech/pykiteconnect#86]
Connection closed: 1006 - connection was closed uncleanly (I dropped the WebSocket TCP connection: close reason without close code)

when i subscribe list of instruments i received above error. then how receive multiple instruments ticks

`# Assign the callbacks
watch_list = [int(i) for i in tsht.range("A2").expand('down').value]
# [779521, 738561, 1102337]

def on_connect(ws, response):
    ws.subscribe([watch_list])
    ws.set_mode(ws.MODE_QUOTE, [watch_list])

kws.on_ticks = on_ticks
kws.on_connect = on_connect
kws.connect()`

**Comment by vijaykz** [comment]
Parameter of `ws.subscribe` should be a list.  From the looks, it seems your passing a list of list.  
Try: 
```
ws.subscribe(watch_list)
ws.set_mode(ws.MODE_QUOTE, watch_list)

```

**Comment by karthickbala123** [comment]
@vijaykz Thanks now its working😀🤝👍
