### ISSUE TITLE
Error with token generation

### ISSUE THREAD

**Issue by augmen** [zerodhatech/pykiteconnect#95]
My script used to work perfectly well till Nov 5. From today showing the error.

```
line 21, in kite_trade
self.kite_loginer.update_access_token()
line 39, in update_access_token
request_token = self._get_request_token()
line 65, in _get_request_token
return json.loads(resp.text)['token']
KeyError: 'token'
```

**Comment by augmen** [comment]
Myscript looks like this 
`resp = s.get(KITE_CONNECT, params={'api_key': self.api_key})
            return json.loads(resp.text)['request_token']`

**Comment by augmen** [comment]
@vividr plz guide

**Comment by augmen** [comment]
@vividvilla plz guide

**Comment by vividvilla** [comment]
Request token is supposed to be copied from redirect URL after successful Kite connect login flow. Seems like you are typing to automate it so I am not sure what you are doing wrong. You and ask your questions on [Kite connect forum here](https://kite.trade/forum/).
